version: '3.8'

services:
  backend:
    image: ${DOCKER_USERNAME}/resumemaker:latest
    container_name: resumemaker-backend
    ports:
      - "8080:8080"
    restart: always
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - BREVO_API_KEY=${BREVO_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - FRONTEND_URL=${FRONTEND_URL}
      - EMAIL_MICROSERVICE_URL=${EMAIL_MICROSERVICE_URL}
