spring.datasource.url=jdbc:postgresql://ep-dawn-sky-aefwo5o1-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_kS79AJLiYuGy

spring.datasource.driver-class-name=org.postgresql.Driver
brevo.api.key=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

groq.api.key=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     

groq.api.url=https://api.groq.com/openai/v1/chat/completions

groq.model=openai/gpt-oss-120b


groq.timeout=120000        
groq.retry.max=5
groq.retry.delay=2000      


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
